import { StyleSheet, Dimensions, Platform } from 'react-native';
import {
  responsiveWidth,
  responsiveHeight,
  responsiveFontSize,
  responsivePadding,
  getGridColumns,
  getCardWidth,
  getSafeAreaPadding,
  getDeviceType,
  SCREEN_WIDTH,
  SCREEN_HEIGHT
} from '../utils/responsiveUtils';

const { width: screenWidth } = Dimensions.get('window');
const deviceType = getDeviceType();
const safeArea = getSafeAreaPadding();
const gridColumns = getGridColumns();
const cardWidth = getCardWidth();

// iPhone-specific adjustments
const isIPhone = Platform.OS === 'ios';
const hasNotch = isIPhone && SCREEN_HEIGHT >= 812;

export const exercisesStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: safeArea.horizontal,
    paddingTop: Platform.OS === 'ios' ? responsiveHeight(0) : responsiveHeight(4),
    paddingBottom: responsivePadding(8),
  },
  backButton: {
    padding: 2,
  },
  headerTitle: {
    color: '#000000',
    fontSize: responsiveFontSize(15),
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  filterButton: {
    padding: 2,
  },
  topTabs: {
    flexDirection: 'row',
    paddingHorizontal: safeArea.horizontal,
    marginTop: responsivePadding(6),
  },
  topTab: {
    paddingHorizontal: responsivePadding(16),
    paddingVertical: responsivePadding(8),
    borderRadius: responsivePadding(16),
    backgroundColor: 'rgba(0,0,0,0.06)',
    marginRight: responsivePadding(8),
  },
  topTabActive: {
    backgroundColor: '#000000',
  },
  topTabText: {
    color: '#000000',
    fontSize: responsiveFontSize(14),
    fontWeight: '600',
  },
  topTabTextActive: {
    color: '#FFFFFF',
  },
  primaryCta: {
    backgroundColor: '#000000',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
  },
  primaryCtaText: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  topOptionsContainer: {
    marginTop: responsivePadding(16),
    // Reduce extra space below the stretches card section
    marginBottom: responsivePadding(8),
    paddingHorizontal: safeArea.horizontal,
  },
  topOptionsTitle: {
    color: '#000000',
    fontSize: responsiveFontSize(18),
    fontWeight: '700',
    marginBottom: responsivePadding(10),
  },
  topOptionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  topOptionCard: {
    width: cardWidth,
    backgroundColor: '#F8F9FA',
    borderRadius: responsivePadding(12),
    paddingVertical: responsivePadding(10),
    paddingHorizontal: responsivePadding(8),
    alignItems: 'center',
    marginBottom: responsivePadding(12),
    marginRight: gridColumns === 2 ? responsivePadding(8) : 0,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  topOptionIconHolder: {
    width: responsiveWidth(36),
    height: responsiveHeight(36),
    borderRadius: responsiveWidth(18),
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: responsivePadding(8),
  },
  topOptionCardTitle: {
    fontSize: responsiveFontSize(12),
    fontWeight: '600',
    color: '#000000',
    textAlign: 'center',
    marginBottom: responsivePadding(2),
  },
  topOptionCardSubtitle: {
    fontSize: responsiveFontSize(10),
    color: '#666666',
    textAlign: 'center',
  },
  topOptionsRow: {
    flexDirection: 'row',
    justifyContent: gridColumns === 2 ? 'flex-start' : 'space-between',
    marginBottom: responsivePadding(12),
  },
  gridContainer: {
    paddingHorizontal: safeArea.horizontal,
    marginTop: responsivePadding(18),
    marginBottom: responsivePadding(8),
  },
  gridTitle: {
    color: '#000000',
    fontSize: responsiveFontSize(18),
    fontWeight: '700',
    marginBottom: responsivePadding(22),
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  gridCard: {
    width: cardWidth,
    backgroundColor: '#F8F9FA',
    borderRadius: responsivePadding(12),
    paddingVertical: responsivePadding(16),
    paddingHorizontal: responsivePadding(12),
    alignItems: 'center',
    marginBottom: responsivePadding(12),
    marginRight: gridColumns === 2 ? responsivePadding(8) : 0,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  gridIconHolder: {
    width: responsiveWidth(40),
    height: responsiveHeight(40),
    borderRadius: responsiveWidth(20),
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: responsivePadding(8),
  },
  gridCardText: {
    fontSize: responsiveFontSize(12),
    fontWeight: '600',
    color: '#000000',
    textAlign: 'center',
    lineHeight: responsiveFontSize(16),
  },
  sectionLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#666666',
    marginBottom: 12,
    marginTop: 10,
  },
  nutritionTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
    marginBottom: 16,
  },
  nutritionTopCard: {
    width: '48%',
    backgroundColor: '#F8F9FA',
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 12,
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  nutritionHalfCard: {
    width: '48%',
    backgroundColor: '#F8F9FA',
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 12,
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  nutritionTopIconHolder: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  nutritionTopCardTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#000000',
    textAlign: 'center',
    marginBottom: 4,
  },
  nutritionTopCardSubtitle: {
    fontSize: 12,
    color: '#666666',
    textAlign: 'center',
  },
  exerciseListContent: {
    paddingHorizontal: safeArea.horizontal,
    paddingTop: responsivePadding(16),
  },
  listControls: {
    paddingHorizontal: safeArea.horizontal,
    paddingVertical: responsivePadding(12),
    backgroundColor: '#F8F9FA',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.06)',
  },
  searchInput: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    paddingHorizontal: 0,
    paddingVertical: 0,
    fontSize: 15,
    borderWidth: 0,
    borderColor: 'transparent',
    marginBottom: 0,
  },
  searchInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingHorizontal: 12,
    minHeight: 44,
    marginBottom: 10,
  },
  filtersRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  sortChip: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E5E7EB',
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    marginRight: 8,
  },
  sortChipActive: {
    backgroundColor: '#000000',
    borderColor: '#000000',
  },
  sortChipText: {
    color: '#111827',
    fontSize: 12,
    fontWeight: '600',
  },
  sortChipTextActive: {
    color: '#FFFFFF',
  },
  sortButton: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  sortButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#000000',
    marginRight: 4,
  },
  exerciseCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#E5E5E5',
  },
  exerciseContent: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
  },
  thumbContainer: {
    width:80,
    height: 80,
    borderRadius: 13,
    overflow: 'hidden',
    backgroundColor: '#F5F5F5',
    position: 'relative',
    marginRight: 12,
  },
  thumbImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain', // Show full image without cropping
  },
  difficultyBadge: {
    position: 'absolute',
    top: 4,
    left: 4,
    width: 18,
    height: 18,
    borderRadius: 9,
    justifyContent: 'center',
    alignItems: 'center',
  },
  difficultyBadgeText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: '700',
  },
  exerciseThumb: {
    position: 'relative',
    height: responsiveHeight(120),
  },
  exerciseThumbImg: {
    width: '100%',
    height: '100%',
  },
  exerciseImageOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.1)',
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
    padding: responsivePadding(8),
  },
  difficultyBadge: {
    backgroundColor: 'rgba(0,0,0,0.7)',
    borderRadius: responsivePadding(12),
    paddingHorizontal: responsivePadding(8),
    paddingVertical: responsivePadding(4),
  },
  difficultyBadgeText: {
    color: '#FFFFFF',
    fontSize: responsiveFontSize(12),
    fontWeight: '600',
  },
  impactContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: responsivePadding(4),
  },
  impactDot: {
    width: responsiveWidth(8),
    height: responsiveHeight(8),
    borderRadius: responsiveWidth(4),
    marginRight: responsivePadding(4),
  },
  highImpactDot: {
    backgroundColor: '#FF6B35',
  },
  mediumImpactDot: {
    backgroundColor: '#FFA726',
  },
  exerciseFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: responsivePadding(6),
  },
  durationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  metaText: {
    color: '#666666',
    fontSize: 12,
    fontWeight: '500',
    marginLeft: 4,
  },
  impactText: {
    fontSize: 10,
    fontWeight: '600',
    marginLeft: 2,
  },
  impactDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginRight: 2,
  },
  arrowContainer: {
    padding: 4,
  },
  metaPill: {
    backgroundColor: '#F4F4F5',
    paddingHorizontal: responsivePadding(10),
    paddingVertical: responsivePadding(5),
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#E4E4E7',
  },
  metaPillText: {
    color: '#111111',
    fontSize: responsiveFontSize(11),
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  exerciseDetails: {
    fontSize: responsiveFontSize(11),
    color: '#64748B',
    marginLeft: responsivePadding(4),
  },
  exerciseImpact: {
    fontSize: responsiveFontSize(11),
    fontWeight: '700',
  },
  highImpact: {
    color: '#FF6B35',
  },
  mediumImpact: {
    color: '#FFA726',
  },
  exerciseImage: {
    width: '100%',
    height: responsiveHeight(120),
  },
  textContent: {
    flex: 1,
    marginRight: 8,
  },
  exerciseTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#000000',
    lineHeight: 20,
    marginBottom: 6,
  },
  exerciseDuration: {
    backgroundColor: '#F5F5F5',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  exerciseDurationText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#000000',
  },
  exerciseMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  exerciseDifficulty: {
    backgroundColor: '#E3F2FD',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 2,
    marginRight: 8,
  },
  exerciseDifficultyText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#1976D2',
  },
  exerciseImpact: {
    backgroundColor: '#FFF3E0',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  exerciseImpactText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#F57C00',
  },
  exerciseDescription: {
    fontSize: 14,
    color: '#666666',
    lineHeight: 20,
  },
  detailContent: {
    padding: 4,
    paddingBottom: 20,
  },
  exerciseHeader: {
    marginBottom: 4,
  },
  exerciseName: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#000000',
    textAlign: 'center',
  },
  mainTimerSection: {
    alignItems: 'center',
    marginBottom: 0,
  },
  circularTimerContainer: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 0,
  },
  timerSvg: {
    position: 'absolute',
  },
  exerciseImageContainer: {
    width: 240,
    height: 240,
    borderRadius: 120,
    overflow: 'hidden',
    backgroundColor: '#F5F5F5',
  },
  exerciseImage: {
    width: '100%',
    height: '100%',
  },
  // Nutrition Library - containers and headings
  gridContainer: {
    paddingHorizontal: 16,
    paddingTop: 8,
  },
  gridTitle: {
    color: '#000000',
    fontSize: 18,
    fontWeight: 'bold',
    letterSpacing: 1,
    marginTop: 6,
    marginBottom: 10,
  },
  sectionLabel: {
    color: '#64748B',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 6,
    marginBottom: 8,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  gridCard: {
    width: '30%',
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 8,
    marginBottom: 10,
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 1,
  },
  gridIconHolder: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  gridCardText: {
    color: '#000000',
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
  nutritionHalfCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 10,
    marginRight: 8,
    marginBottom: 10,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 1,
  },
  timerDisplay: {
    fontSize: 48,
    fontWeight: 'bold',
    color: '#000000',
    marginBottom: 8,
  },
  timerControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 24,
  },
  controlButton: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#F5F5F5',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 10,
  },
  playButton: {
    backgroundColor: '#000000',
    width: 80,
    height: 80,
    borderRadius: 40,
  },
  exerciseHeroSection: {
    marginBottom: 30,
  },
  exerciseHeroImageContainer: {
    width: '100%',
    height: 200,
    borderRadius: 12,
    overflow: 'hidden',
    marginBottom: 16,
  },
  exerciseHeroImage: {
    width: '100%',
    height: '100%',
  },
  exerciseHeroContent: {
    paddingHorizontal: 4,
  },
  exerciseHeroTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#000000',
    marginBottom: 8,
  },
  exerciseHeroMeta: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  exerciseHeroDuration: {
    backgroundColor: '#E3F2FD',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  exerciseHeroDifficulty: {
    backgroundColor: '#E8F5E8',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  exerciseHeroImpact: {
    backgroundColor: '#FFF3E0',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  exerciseStepsSection: {
    marginBottom: 0,
  },
  exerciseStepsTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#000000',
    marginBottom: 24,
    letterSpacing: -0.3,
  },
  exerciseStep: {
    flexDirection: 'row',
    marginBottom: 20,
    alignItems: 'flex-start',
  },
  exerciseStepNumber: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#000000',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
    marginTop: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  exerciseStepNumberText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  exerciseStepText: {
    flex: 1,
    fontSize: 16,
    color: '#333333',
    lineHeight: 24,
    fontWeight: '500',
  },
  exerciseBenefitsSection: {
    marginBottom: 0,
  },
  exerciseBenefitsTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#000000',
    marginBottom: 24,
    letterSpacing: -0.3,
  },
  // Nutrition Detail View styles
  detailContent: {
    padding: 16,
    paddingBottom: 80,
    backgroundColor: '#FFFFFF',
  },
  detailTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#000000',
    marginBottom: 8,
  },
  sectionHeading: {
    fontSize: 14,
    fontWeight: '700',
    color: '#64748B',
    marginBottom: 12,
  },
  nutritionItemsList: {
    gap: 12,
  },
  nutritionItemsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 10,
  },
  nutritionItemCardHalf: {
    width: '48%',
  },
  nutritionItemCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 1,
    overflow: 'hidden',
  },
  nutritionItemImage: {
    width: '100%',
    height: 160,
    backgroundColor: '#F1F5F9',
  },
  nutritionItemImageContent: {
    width: '100%',
    height: '100%',
  },
  nutritionItemContent: {
    padding: 10,
  },
  nutritionItemName: {
    fontSize: 14,
    fontWeight: '700',
    color: '#000000',
    marginBottom: 4,
  },
  nutritionItemType: {
    fontSize: 12,
    fontWeight: '600',
    color: '#94A3B8',
    marginBottom: 8,
  },
  nutritionItemDescription: {
    fontSize: 11,
    color: '#334155',
    lineHeight: 16,
    marginBottom: 6,
  },
  nutritionItemBenefits: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 6,
  },
  nutritionBenefitChip: {
    backgroundColor: '#F1F5F9',
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  nutritionBenefitText: {
    fontSize: 12,
    color: '#0F172A',
    fontWeight: '600',
  },
  nutritionItemFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  nutritionItemServing: {
    fontSize: 12,
    color: '#475569',
    fontWeight: '600',
  },
  nutritionGrowthScore: {
    backgroundColor: '#000000',
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  nutritionGrowthScoreText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
  exerciseBenefit: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 16,
    paddingLeft: 4,
  },
  exerciseBenefitText: {
    flex: 1,
    fontSize: 16,
    color: '#333333',
    lineHeight: 24,
    fontWeight: '500',
    marginLeft: 14,
  },
  subExercisesContainer: {
    padding: 16,
  },
  subExercisesTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#000000',
    marginBottom: 16,
    textAlign: 'center',
  },
  subExerciseCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    marginBottom: 10,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#F0F0F0',
  },
  subExerciseContent: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
  },
  subExerciseNumberContainer: {
    marginRight: 10,
  },
  subExerciseNumber: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#000000',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
  },
  subExerciseNumberText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
  subExerciseInfo: {
    flex: 1,
    marginRight: 6,
  },
  subExerciseName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#000000',
    marginBottom: 2,
    lineHeight: 16,
  },
  subExerciseDescription: {
    fontSize: 12,
    color: '#666666',
    lineHeight: 14,
    marginBottom: 4,
  },
  subExerciseDurationBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8F9FA',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
    alignSelf: 'flex-start',
  },
  subExerciseDurationText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#666666',
    marginLeft: 4,
  },
  subExerciseArrow: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#F8F9FA',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dailyExercisesSection: {
    marginBottom: 24,
  },
  sectionSubtitle: {
    fontSize: 14,
    color: '#666666',
    marginBottom: 16,
    fontWeight: '500',
  },
  dailyExerciseCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    marginBottom: 10,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 1,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.05)',
  },
  dailyExerciseCardCompleted: {
    backgroundColor: '#F0FDF4',
    borderColor: '#10B981',
    borderWidth: 1,
  },
  dailyExerciseContent: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
  },
  dailyExerciseInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  dailyExerciseNumberContainer: {
    marginRight: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dailyExerciseNumber: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#000000',
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: 28,
  },
  dailyExerciseDetails: {
    flex: 1,
  },
  dailyExerciseName: {
    fontSize: 15,
    fontWeight: '600',
    color: '#000000',
    marginBottom: 2,
  },
  dailyExerciseNameCompleted: {
    color: '#10B981',
    textDecorationLine: 'line-through',
  },
  dailyExerciseMeta: {
    fontSize: 13,
    color: '#666666',
  },
  dailyExerciseActions: {
    paddingLeft: 12,
  },
  quickActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 16,
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F8F9FA',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginHorizontal: 4,
  },
  secondaryButton: {
    backgroundColor: '#F0F9FF',
  },
  actionButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#3B5FE3',
    marginLeft: 8,
  },
  loadingContainer: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  loadingText: {
    fontSize: 16,
    color: '#666666',
  },
  errorContainer: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  errorText: {
    fontSize: 16,
    color: '#FF6B6B',
  },
  phaseBadge: {
    backgroundColor: '#E3F2FD',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    alignSelf: 'flex-start',
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#000000',
    marginBottom: 8,
  },
  barcodeInputModal: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  barcodeInputContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 24,
    width: '90%',
    maxWidth: 400,
  },
  barcodeInputTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#000000',
    marginBottom: 8,
    textAlign: 'center',
  },
  barcodeInputSubtitle: {
    fontSize: 14,
    color: '#666666',
    marginBottom: 20,
    textAlign: 'center',
  },
  barcodeInput: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 16,
    marginBottom: 20,
  },
  barcodeInputButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  barcodeCancelButton: {
    flex: 1,
    backgroundColor: '#F5F5F5',
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
    marginRight: 8,
  },
  barcodeCancelButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#666666',
  },
  barcodeLookupButton: {
    flex: 1,
    backgroundColor: '#3B5FE3',
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
    marginLeft: 8,
  },
  barcodeLookupButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  completionModalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  completionModal: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 24,
    width: '90%',
    maxWidth: 400,
    alignItems: 'center',
  },
  completionIconContainer: {
    marginBottom: 16,
  },
  completionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#000000',
    marginBottom: 12,
    textAlign: 'center',
  },
  completionMessage: {
    fontSize: 16,
    color: '#666666',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 24,
  },
  completionButton: {
    backgroundColor: '#3B5FE3',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 24,
    width: '100%',
    alignItems: 'center',
  },
  completionButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  timerImageContainer: {
    width: 240,
    height: 240,
    borderRadius: 120,
    overflow: 'hidden',
    backgroundColor: '#F5F5F5',
    borderWidth: 2,
    borderColor: '#E8E8E8',
  },
  timerExerciseImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain', // Show full image without cropping
  },
  timerTextContainer: {
    position: 'absolute',
    bottom: 20,
    left: 0,
    right: 0,
    alignItems: 'center',
  },
  timerText: {
    fontSize: 48,
    fontWeight: '700',
    color: '#000000',
    letterSpacing: -1,
  },
  timerPlayButton: {
    backgroundColor: '#000000',
    width: 88,
    height: 88,
    borderRadius: 44,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  timerPlayButtonActive: {
    backgroundColor: '#000000',
  },
  timerControlButton: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#000000',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
  // WeeklyProgressView styles
  weekContainer: {
    marginBottom: responsivePadding(24),
    paddingHorizontal: responsivePadding(20),
  },
  weekHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: responsivePadding(12),
  },
  weekTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: responsivePadding(8),
  },
  weekIcon: {
    width: responsiveWidth(32),
    height: responsiveHeight(32),
    borderRadius: responsiveWidth(16),
    backgroundColor: '#F0F0F0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  weekIconLocked: {
    backgroundColor: '#E0E0E0',
  },
  weekTitle: {
    fontSize: responsiveFontSize(18),
    fontWeight: 'bold',
    color: '#000000',
  },
  weekTitleLocked: {
    color: '#999999',
  },
  weekSubtitle: {
    fontSize: responsiveFontSize(14),
    color: '#666666',
    marginTop: responsivePadding(2),
  },
  weekStatus: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  statusText: {
    fontSize: responsiveFontSize(14),
    fontWeight: '600',
    color: '#4CD964',
    marginRight: responsivePadding(8),
  },
  statusTextLocked: {
    color: '#999999',
  },
  weekContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: responsivePadding(12),
    padding: responsivePadding(16),
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  weekContentLocked: {
    opacity: 0.5,
  },
  daysContainer: {
    alignItems: 'center',
    marginBottom: responsivePadding(16),
  },
  dayRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: responsivePadding(8),
  },
  dayCircle: {
    width: responsiveWidth(40),
    height: responsiveHeight(40),
    borderRadius: responsiveWidth(20),
    backgroundColor: '#F5F5F5',
    borderWidth: 2,
    borderColor: '#E0E0E0',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: responsivePadding(4),
    position: 'relative',
  },
  dayCircleCompleted: {
    backgroundColor: '#4CD964',
    borderColor: '#4CD964',
  },
  dayCircleCurrent: {
    backgroundColor: '#000000',
    borderColor: '#000000',
  },
  dayCircleLocked: {
    backgroundColor: '#F5F5F5',
    borderColor: '#E0E0E0',
  },
  dayNumber: {
    fontSize: responsiveFontSize(14),
    fontWeight: '600',
    color: '#000000',
  },
  dayNumberCompleted: {
    color: '#FFFFFF',
  },
  dayNumberCurrent: {
    color: '#FFFFFF',
  },
  dayNumberLocked: {
    color: '#999999',
  },
  completionBadge: {
    position: 'absolute',
    top: responsivePadding(-8),
    right: responsivePadding(-8),
    backgroundColor: '#FFFFFF',
    borderRadius: responsivePadding(12),
    padding: responsivePadding(2),
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  todayExercisesContainer: {
    marginTop: responsivePadding(16),
    paddingTop: responsivePadding(16),
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
  },
  todayExercisesTitle: {
    fontSize: responsiveFontSize(16),
    fontWeight: '600',
    color: '#000000',
    marginBottom: responsivePadding(12),
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  loadingText: {
    fontSize: responsiveFontSize(16),
    color: '#666666',
  },
});
