// Exercises dataset (offline-first)

export const CATEGORIES = [
  { id: 'posture', name: 'Posture' },
  { id: 'masai-jump', name: 'Masai Jump' },
  { id: 'upper-body', name: 'Upper Body' },
  { id: 'lower-body', name: 'Lower Body' },
  { id: 'feet-ankles', name: 'Feet & Ankles' },
  { id: 'chest', name: 'Chest' },
  { id: 'neck', name: 'Neck' },
  { id: 'shoulders', name: 'Shoulders' },
  { id: 'hands', name: 'Hands' },
  { id: 'stretching', name: 'Stretching' },
  { id: 'strength', name: 'Strength' },
  { id: 'recovery', name: 'Recovery' },
];

// difficulty: 'Beginner' | 'Intermediate' | 'Advanced'
// impact: 'Low' | 'Medium' | 'High'

export const EXERCISES = [
  {
    id: 'ex-001',
    name: 'Hanging Stretch',
    categoryId: 'stretching',
    durationMin: 10,
    difficulty: 'Beginner',
    impact: 'High',
    icon: 'fitness',
    shortDescription: 'Spinal decompression and shoulder opening.',
    benefits: [
      'Decompresses spine and improves posture',
      'Opens shoulders and lats',
      'Relieves lower back tension',
    ],
    targetMuscles: ['Spine', 'Lats', 'Shoulders'],
    equipment: ['Bar (optional)'],
    steps: [
      'Grip a stable overhead bar with both hands.',
      'Let your body hang, keeping shoulders engaged.',
      'Breathe steadily for 20–30 seconds; repeat 3–5 times.',
    ],
  },
  {
    id: 'ex-002',
    name: 'Cobra Stretch',
    categoryId: 'stretching',
    durationMin: 8,
    difficulty: 'Beginner',
    impact: 'Medium',
    icon: 'body',
    shortDescription: 'Thoracic extension and hip flexor opener.',
    benefits: ['Promotes spinal extension', 'Opens chest', 'Reduces slouching'],
    targetMuscles: ['Spine extensors', 'Hip flexors', 'Chest'],
    equipment: [],
    steps: [
      'Lie prone, hands under shoulders.',
      'Press chest up, shoulders down and back.',
      'Hold 20–30s; repeat 3–4 times.',
    ],
  },
  {
    id: 'ex-003',
    name: 'Bridge Pose',
    categoryId: 'posture',
    durationMin: 12,
    difficulty: 'Intermediate',
    impact: 'Medium',
    icon: 'body',
    shortDescription: 'Glute activation and spine articulation.',
    benefits: ['Engages posterior chain', 'Stabilizes core', 'Supports posture'],
    targetMuscles: ['Glutes', 'Hamstrings', 'Core'],
    equipment: [],
    steps: [
      'Lie supine, knees bent, feet hip-width.',
      'Press through heels to lift hips, squeeze glutes.',
      'Lower slowly; 10–12 reps for 2–3 sets.',
    ],
  },
  {
    id: 'ex-004',
    name: 'Wall Stretches',
    categoryId: 'posture',
    durationMin: 15,
    difficulty: 'Beginner',
    impact: 'High',
    icon: 'home',
    shortDescription: 'Thoracic mobility and shoulder opening at wall.',
    benefits: ['Improves thoracic mobility', 'Opens chest', 'Enhances posture'],
    targetMuscles: ['Thoracic spine', 'Shoulders'],
    equipment: ['Wall'],
    steps: [
      'Stand facing wall, forearms on wall.',
      'Sink chest forward while keeping ribs down.',
      'Hold 20s; 3–5 rounds.',
    ],
  },
  {
    id: 'ex-005',
    name: 'Pelvic Tilt',
    categoryId: 'posture',
    durationMin: 7,
    difficulty: 'Beginner',
    impact: 'Medium',
    icon: 'body',
    shortDescription: 'Core control for lumbar neutrality.',
    benefits: ['Strengthens deep core', 'Reduces lumbar sway', 'Body awareness'],
    targetMuscles: ['Core', 'Lower back'],
    equipment: [],
    steps: [
      'Lie supine, knees bent.',
      'Gently tuck pelvis to press low back into floor.',
      'Hold 3–5s; 12–15 reps.',
    ],
  },
  {
    id: 'ex-006',
    name: 'Masai Jump Drill',
    categoryId: 'lower-body',
    durationMin: 6,
    difficulty: 'Beginner',
    impact: 'High',
    icon: 'flash',
    shortDescription: 'Rhythmic vertical jumps with soft landings.',
    benefits: ['Ankle stiffness', 'Calf activation', 'Explosive control'],
    targetMuscles: ['Calves', 'Quads', 'Ankles'],
    equipment: [],
    steps: [
      'Stand tall, feet hip-width.',
      'Perform quick vertical hops, minimal knee bend.',
      'Land softly; 3 rounds of 30–45s.',
    ],
  },
  {
    id: 'ex-007',
    name: 'Shoulder Circles',
    categoryId: 'shoulders',
    durationMin: 6,
    difficulty: 'Beginner',
    impact: 'Low',
    icon: 'refresh',
    shortDescription: 'Gentle mobility for shoulder joint.',
    benefits: ['Lubricates joint', 'Warms rotator cuff', 'Improves range'],
    targetMuscles: ['Delts', 'Rotator cuff'],
    equipment: [],
    steps: ['Slow circles forward', 'Slow circles backward', 'Control and breathe'],
  },
  {
    id: 'ex-008',
    name: 'Neck Flex/Ext',
    categoryId: 'neck',
    durationMin: 5,
    difficulty: 'Beginner',
    impact: 'Low',
    icon: 'arrow-up-down',
    shortDescription: 'Controlled neck mobility.',
    benefits: ['Relieves stiffness', 'Improves control'],
    targetMuscles: ['Cervical flexors', 'Extensors'],
    equipment: [],
    steps: ['Tuck chin slightly', 'Nod yes/no slowly', 'Stay within comfort'],
  },
  {
    id: 'ex-009',
    name: 'Chest Opener',
    categoryId: 'chest',
    durationMin: 8,
    difficulty: 'Beginner',
    impact: 'Medium',
    icon: 'expand',
    shortDescription: 'Pec and anterior delt stretch.',
    benefits: ['Opens chest', 'Counters rounded shoulders'],
    targetMuscles: ['Pecs', 'Anterior delts'],
    equipment: ['Wall/doorframe'],
    steps: ['Place forearm on wall', 'Rotate torso away', 'Hold 20–30s'],
  },
  {
    id: 'ex-010',
    name: 'Ankle Mobility',
    categoryId: 'feet-ankles',
    durationMin: 6,
    difficulty: 'Beginner',
    impact: 'Low',
    icon: 'footsteps',
    shortDescription: 'Dorsiflexion drill for ankles.',
    benefits: ['Improves dorsiflexion', 'Smoother squats and landings'],
    targetMuscles: ['Calves', 'Tibialis'],
    equipment: [],
    steps: ['Knee-to-wall rocks', 'Heel stays down', 'Smooth reps 10–12 each side'],
  },
  {
    id: 'ex-011',
    name: 'Thoracic Cat-Cow',
    categoryId: 'posture',
    durationMin: 6,
    difficulty: 'Beginner',
    impact: 'Low',
    icon: 'body',
    shortDescription: 'Segmental spinal flexion/extension.',
    benefits: ['Mobilizes thoracic spine', 'Improves posture awareness'],
    targetMuscles: ['Spine', 'Core'],
    equipment: [],
    steps: ['On all fours', 'Alternate arch and round', 'Slow breathing 8–10 reps'],
  },
  {
    id: 'ex-012',
    name: 'Scapular Wall Slides',
    categoryId: 'shoulders',
    durationMin: 8,
    difficulty: 'Beginner',
    impact: 'Medium',
    icon: 'home',
    shortDescription: 'Wall-guided overhead reach.',
    benefits: ['Strengthens upward rotation', 'Opens chest'],
    targetMuscles: ['Serratus', 'Lower traps', 'Delts'],
    equipment: ['Wall'],
    steps: ['Back to wall', 'Slide arms up keeping ribs down', 'Control 8–12 reps'],
  },
  {
    id: 'ex-013',
    name: 'Doorway Pec Stretch',
    categoryId: 'chest',
    durationMin: 6,
    difficulty: 'Beginner',
    impact: 'Low',
    icon: 'home',
    shortDescription: 'Open the front line.',
    benefits: ['Relieves rounded shoulders', 'Opens pecs'],
    targetMuscles: ['Pecs'],
    equipment: ['Doorway'],
    steps: ['Forearm on frame', 'Turn torso away', 'Hold 20–30s each side'],
  },
  {
    id: 'ex-014',
    name: 'Hip Flexor Lunge Stretch',
    categoryId: 'lower-body',
    durationMin: 8,
    difficulty: 'Beginner',
    impact: 'Medium',
    icon: 'body',
    shortDescription: 'Opens front hip.',
    benefits: ['Counters sitting', 'Improves pelvic position'],
    targetMuscles: ['Hip flexors', 'Quads'],
    equipment: [],
    steps: ['Half-kneel', 'Posteriorly tilt pelvis', 'Shift forward and hold'],
  },
  {
    id: 'ex-015',
    name: 'Hamstring Hinge',
    categoryId: 'lower-body',
    durationMin: 7,
    difficulty: 'Beginner',
    impact: 'Low',
    icon: 'body',
    shortDescription: 'Active hamstring lengthening.',
    benefits: ['Improves hinge pattern', 'Lengthens posterior chain'],
    targetMuscles: ['Hamstrings'],
    equipment: [],
    steps: ['One heel forward', 'Hinge with flat back', 'Pulse 10–12 reps'],
  },
  {
    id: 'ex-016',
    name: 'Wall Ankle Dorsiflexion',
    categoryId: 'feet-ankles',
    durationMin: 6,
    difficulty: 'Beginner',
    impact: 'Low',
    icon: 'home',
    shortDescription: 'Knee-to-wall drill.',
    benefits: ['Increases dorsiflexion', 'Better squat mechanics'],
    targetMuscles: ['Calves', 'Tibialis'],
    equipment: ['Wall'],
    steps: ['Toe a few cm from wall', 'Touch knee to wall without heel lift', '10–12 reps'],
  },
  {
    id: 'ex-017',
    name: 'Reverse Plank',
    categoryId: 'upper-body',
    durationMin: 6,
    difficulty: 'Intermediate',
    impact: 'Medium',
    icon: 'body',
    shortDescription: 'Posterior chain isometric.',
    benefits: ['Opens shoulders', 'Strengthens posterior chain'],
    targetMuscles: ['Shoulders', 'Glutes', 'Hamstrings'],
    equipment: [],
    steps: ['Hands behind hips', 'Lift chest and hips', 'Hold 20–30s, 3 rounds'],
  },
  {
    id: 'ex-018',
    name: 'Prone Y-T-W',
    categoryId: 'upper-body',
    durationMin: 8,
    difficulty: 'Intermediate',
    impact: 'Medium',
    icon: 'body',
    shortDescription: 'Scapular control series.',
    benefits: ['Lower trap activation', 'Posture support'],
    targetMuscles: ['Lower traps', 'Rear delts'],
    equipment: [],
    steps: ['Lie prone', 'Raise arms in Y, T, W', '2–3 sets of 8 each'],
  },
  {
    id: 'ex-019',
    name: 'Wrist Extension Stretch',
    categoryId: 'hands',
    durationMin: 5,
    difficulty: 'Beginner',
    impact: 'Low',
    icon: 'hand',
    shortDescription: 'Relieve tight forearms.',
    benefits: ['Better push-up position', 'Healthier wrists'],
    targetMuscles: ['Forearm flexors'],
    equipment: [],
    steps: ['Palm down, fingers forward', 'Lean gently', 'Hold 20s'],
  },
  {
    id: 'ex-020',
    name: 'Wrist Flexion Stretch',
    categoryId: 'hands',
    durationMin: 5,
    difficulty: 'Beginner',
    impact: 'Low',
    icon: 'hand',
    shortDescription: 'Balance wrist mobility.',
    benefits: ['Relieves strain', 'Improves hand function'],
    targetMuscles: ['Forearm extensors'],
    equipment: [],
    steps: ['Palm up, fingers toward you', 'Lean gently', 'Hold 20s'],
  },
  {
    id: 'ex-021',
    name: 'Neck Side Bends',
    categoryId: 'neck',
    durationMin: 5,
    difficulty: 'Beginner',
    impact: 'Low',
    icon: 'arrow-back',
    shortDescription: 'Lateral neck mobility.',
    benefits: ['Reduces stiffness', 'Improves range'],
    targetMuscles: ['Upper traps', 'Scalenes'],
    equipment: [],
    steps: ['Ear toward shoulder', 'Gentle holds 15–20s'],
  },
  {
    id: 'ex-022',
    name: 'Calf Raises (Tempo)',
    categoryId: 'lower-body',
    durationMin: 8,
    difficulty: 'Beginner',
    impact: 'Medium',
    icon: 'arrow-up',
    shortDescription: 'Controlled plantarflexion.',
    benefits: ['Ankle strength', 'Landing capacity'],
    targetMuscles: ['Calves'],
    equipment: [],
    steps: ['Rise for 2s', 'Hold 1s', 'Lower 2–3s, 12 reps'],
  },
  {
    id: 'ex-023',
    name: 'Quadruped T-Spine Rotation',
    categoryId: 'posture',
    durationMin: 6,
    difficulty: 'Beginner',
    impact: 'Low',
    icon: 'refresh',
    shortDescription: 'Thread the needle variant.',
    benefits: ['Thoracic rotation', 'Upper back relief'],
    targetMuscles: ['Thoracic spine'],
    equipment: [],
    steps: ['Hand behind head', 'Rotate elbow up', 'Slow 8–10 reps each'],
  },
  {
    id: 'ex-024',
    name: 'Dead Bug',
    categoryId: 'posture',
    durationMin: 7,
    difficulty: 'Beginner',
    impact: 'Medium',
    icon: 'bug',
    shortDescription: 'Core stability drill.',
    benefits: ['Spine-friendly core', 'Better pelvic control'],
    targetMuscles: ['Core'],
    equipment: [],
    steps: ['Arms up, knees up', 'Opposite arm/leg extend', 'Keep back flat 8–10 each'],
  },
  {
    id: 'ex-025',
    name: 'Standing Wall Angels',
    categoryId: 'shoulders',
    durationMin: 8,
    difficulty: 'Intermediate',
    impact: 'Medium',
    icon: 'home',
    shortDescription: 'Full ROM shoulder pattern.',
    benefits: ['Mobility + control', 'Scapular mechanics'],
    targetMuscles: ['Delts', 'Traps', 'Serratus'],
    equipment: ['Wall'],
    steps: ['Elbows/wrists to wall', 'Slide up/down slowly', '8–10 reps'],
  },
  {
    id: 'ex-026',
    name: 'Isometric Chin Tuck',
    categoryId: 'neck',
    durationMin: 5,
    difficulty: 'Beginner',
    impact: 'Low',
    icon: 'arrow-down',
    shortDescription: 'Deep neck flexor activation.',
    benefits: ['Neck alignment', 'Posture support'],
    targetMuscles: ['Deep cervical flexors'],
    equipment: [],
    steps: ['Gently tuck chin', 'Hold 5s, 8–10 reps'],
  },
  {
    id: 'ex-027',
    name: 'Band Pull-Aparts',
    categoryId: 'upper-body',
    durationMin: 7,
    difficulty: 'Beginner',
    impact: 'Medium',
    icon: 'expand',
    shortDescription: 'Posterior shoulder activation.',
    benefits: ['Balances pressing volume', 'Improves posture'],
    targetMuscles: ['Rear delts', 'Rhomboids'],
    equipment: ['Light band'],
    steps: ['Arms straight', 'Pull band apart to chest', '12–15 reps'],
  },
  {
    id: 'ex-028',
    name: 'Supported Sumo Squat Hold',
    categoryId: 'lower-body',
    durationMin: 6,
    difficulty: 'Beginner',
    impact: 'Medium',
    icon: 'body',
    shortDescription: 'Adductor-friendly squat stretch.',
    benefits: ['Hip opening', 'Ankle/knee alignment'],
    targetMuscles: ['Adductors', 'Glutes'],
    equipment: ['Support'],
    steps: ['Wide stance', 'Sit down with support', 'Hold 20–30s'],
  },
  {
    id: 'ex-029',
    name: "Child's Pose with Side Reach",
    categoryId: 'recovery',
    durationMin: 6,
    difficulty: 'Beginner',
    impact: 'Low',
    icon: 'body',
    shortDescription: 'Restorative lat/QL stretch.',
    benefits: ['Relaxes back', 'Opens lats'],
    targetMuscles: ['Lats', 'QL'],
    equipment: [],
    steps: ['Child’s pose', 'Walk hands to one side', 'Hold and breathe'],
  },
  {
    id: 'ex-030',
    name: 'Wall Calf Stretch',
    categoryId: 'feet-ankles',
    durationMin: 5,
    difficulty: 'Beginner',
    impact: 'Low',
    icon: 'home',
    shortDescription: 'Gastrocnemius focus.',
    benefits: ['Relieves tight calves', 'Improves ankle motion'],
    targetMuscles: ['Calves'],
    equipment: ['Wall'],
    steps: ['Back leg straight', 'Heel down', 'Hold 20–30s'],
  },
  {
    id: 'ex-031',
    name: 'Soleus Wall Stretch',
    categoryId: 'feet-ankles',
    durationMin: 5,
    difficulty: 'Beginner',
    impact: 'Low',
    icon: 'home',
    shortDescription: 'Bent-knee calf stretch.',
    benefits: ['Targets soleus', 'Aids squat depth'],
    targetMuscles: ['Soleus'],
    equipment: ['Wall'],
    steps: ['Front knee bent toward wall', 'Heel down', 'Hold 20–30s'],
  },
  {
    id: 'ex-032',
    name: 'Chest Supported Row (Band)',
    categoryId: 'upper-body',
    durationMin: 8,
    difficulty: 'Beginner',
    impact: 'Medium',
    icon: 'fitness',
    shortDescription: 'Posterior chain pull.',
    benefits: ['Back strength', 'Shoulder balance'],
    targetMuscles: ['Lats', 'Rhomboids'],
    equipment: ['Band'],
    steps: ['Anchor band', 'Row elbows back', '12 reps x 3'],
  },
  {
    id: 'ex-033',
    name: '90/90 Hip Switch',
    categoryId: 'lower-body',
    durationMin: 7,
    difficulty: 'Beginner',
    impact: 'Low',
    icon: 'refresh',
    shortDescription: 'Rotational hip mobility.',
    benefits: ['Improves internal/external rotation'],
    targetMuscles: ['Hips'],
    equipment: [],
    steps: ['Sit in 90/90', 'Switch sides slowly', '8–10 reps'],
  },
  {
    id: 'ex-034',
    name: 'Side Plank',
    categoryId: 'posture',
    durationMin: 6,
    difficulty: 'Intermediate',
    impact: 'Medium',
    icon: 'body',
    shortDescription: 'Lateral core strength.',
    benefits: ['Stabilizes spine', 'Improves posture'],
    targetMuscles: ['Obliques', 'Glute med'],
    equipment: [],
    steps: ['Elbow under shoulder', 'Lift hips', 'Hold 20–30s each side'],
  },
  {
    id: 'ex-035',
    name: 'Standing Chest Expansion',
    categoryId: 'chest',
    durationMin: 5,
    difficulty: 'Beginner',
    impact: 'Low',
    icon: 'expand',
    shortDescription: 'Interlace fingers behind.',
    benefits: ['Opens chest', 'Counters desk posture'],
    targetMuscles: ['Pecs', 'Front delts'],
    equipment: [],
    steps: ['Hands behind', 'Lift chest and hands', 'Hold 15–20s'],
  },
  {
    id: 'ex-036',
    name: 'Seated Nerve Glides',
    categoryId: 'recovery',
    durationMin: 6,
    difficulty: 'Beginner',
    impact: 'Low',
    icon: 'body',
    shortDescription: 'Gentle neural mobility.',
    benefits: ['Relieves tightness', 'Improves comfort'],
    targetMuscles: ['Neural tissue'],
    equipment: [],
    steps: ['Extend leg and ankle', 'Tilt head opposite', 'Slow rhythm 8–10 reps'],
  },
  {
    id: 'ex-037',
    name: 'Wall Slides (Serratus Focus)',
    categoryId: 'shoulders',
    durationMin: 7,
    difficulty: 'Intermediate',
    impact: 'Medium',
    icon: 'home',
    shortDescription: 'Protraction + upward rotation.',
    benefits: ['Scapular control', 'Better overhead reach'],
    targetMuscles: ['Serratus'],
    equipment: ['Wall'],
    steps: ['Forearms on wall', 'Slide and protract', '10–12 reps'],
  },
  {
    id: 'ex-038',
    name: 'Quadruped Rock Back',
    categoryId: 'recovery',
    durationMin: 6,
    difficulty: 'Beginner',
    impact: 'Low',
    icon: 'refresh',
    shortDescription: 'Hips + spine coordination.',
    benefits: ['Gentle mobility', 'Calming movement'],
    targetMuscles: ['Hips', 'Spine'],
    equipment: [],
    steps: ['On all fours', 'Rock hips to heels', 'Slow 10 reps'],
  },
  {
    id: 'ex-039',
    name: 'Scap Push-Ups',
    categoryId: 'upper-body',
    durationMin: 6,
    difficulty: 'Beginner',
    impact: 'Medium',
    icon: 'body',
    shortDescription: 'Protraction/retraction only.',
    benefits: ['Serratus activation', 'Better push-up form'],
    targetMuscles: ['Serratus', 'Traps'],
    equipment: [],
    steps: ['Plank position', 'Push floor away / let chest sink', '10–12 reps'],
  },
  {
    id: 'ex-040',
    name: 'Hip Airplanes (Supported)',
    categoryId: 'lower-body',
    durationMin: 7,
    difficulty: 'Advanced',
    impact: 'High',
    icon: 'airplane',
    shortDescription: 'Hip rotation balance drill.',
    benefits: ['Glute strength', 'Hip control'],
    targetMuscles: ['Glutes', 'Hips'],
    equipment: ['Support'],
    steps: ['Stand on one leg', 'Rotate pelvis open/closed', '5–6 reps each'],
  },
];

// Nutrition data for supplements and other categories
export const NUTRITION_CATEGORIES = [
  { id: 'supplements', name: 'Supplements', icon: 'medical' },
  { id: 'growth-foods', name: 'Growth Foods', icon: 'leaf' },
  { id: 'protein-sources', name: 'Protein Sources', icon: 'fish' },
  { id: 'calcium-rich', name: 'Calcium Rich', icon: 'water' }
];

export default { CATEGORIES, EXERCISES, NUTRITION_CATEGORIES };
